require("core.options")
local plugins = require("core.plugins")
require("core.pack").setup(plugins)
--require("core.custom_plugins")
require("core.keymaps")
require("core.autocmds")
require("core.functions")
