require("plugins.treesitter")
require("plugins.telescope")
require("plugins.comment")
require("plugins.lsp")
require("plugins.lsp_signature")
require("plugins.ui")
require("plugins.cmp")
require("plugins.mini_files")
require("plugins.nvim-navic")
require("plugins.bufferline")
require("plugins.gitsigns")

-- colorschemes
require("plugins.catpuccin")
require("plugins.github-nvim-theme")
